services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "55432:5432"
    networks:
      - db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
      target: deploy
    container_name: backend
    env_file:
      /server/.env
    depends_on:
      - postgres
    ports:
      - '3000:3000'
    networks:
      - db
    command: >
      sh -c "
        npx prisma migrate deploy &&
        node dist/main.js
      "

networks:
  db:
    driver: bridge