version: '3.9'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-secret}
      POSTGRES_USER: ${POSTGRES_USER:-secret}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secret}
    ports:
      - "55532:5432"
    networks:
      - db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-secret}" ]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./server
      dockerfile: dev.Dockerfile
    container_name: backend
    command: sh -c "npx prisma migrate deploy && npx prisma generate && npm run start:dev"
    volumes:
      - ./avatars:/app/avatars
      - ./uploads:/app/uploads
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=${PORT:-3001}
      - SALT_ROUNDS=${SALT_ROUNDS:-10}
      - JWT_SECRET=${JWT_SECRET:-MYJWTSECRET}
      - DATABASE_URL=postgresql://${POSTGRES_USER:-secret}:${POSTGRES_PASSWORD:-secret}@postgres:5432/${POSTGRES_DB:-secret}?schema=public
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "${PORT:-3001}:3001"
    networks:
      - db
      - web

  frontend:
    build:
      context: ./client
      dockerfile: dev.Dockerfile
    container_name: frontend
    command: npm run dev
    working_dir: /app
    ports:
      - "${CLIENT_PORT:-3000}:3000"
    environment:
      - HOST=${HOST:-0.0.0.0}
      - PORT=${CLIENT_PORT:-3000}
      - NODE_ENV=${NODE_ENV:-development}
      - API_URL=${CLIENT_API_URL:-http://localhost:3001/api}
      - SSR_API_URL=${CLIENT_SSR_API_URL:-http://backend:3001/api}
      - STATIC_URL=${CLIENT_STATIC_URL:-http://localhost:3001}
    volumes:
      - ./client:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    networks:
      - web

networks:
  db:
    driver: bridge
  web:
    driver: bridge
