export enum ErrorCodes {
  INCORRECT_AVATAR = 1,
  USER_ALREADY_EXISTS = 2,
  UNAUTHORIZED = 3,
  INCORRECT_PHOTO = 4,
  ANNOUNCEMENT_NOT_BELONG_YOY = 5,
  ANNOUNCEMENT_NOT_FOUND = 6,
  CHAT_WITH_YOURSELF = 7,
  DATA_VALIDATION_ERROR = 100,
  INTERNAL_SERVER_ERROR = 500,
}
